routes/web.php
<?php

// cms
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\cms\DashboardController;
use App\Http\Controllers\cms\UserController;
use App\Http\Controllers\cms\AuthController;
use App\Http\Controllers\cms\CourseController;
use App\Http\Controllers\cms\KategoriBlogController;
use App\Http\Controllers\cms\BlogController as CmsBlog;
use App\Http\Controllers\cms\LibraryController as CmsLibrary;
use App\Http\Controllers\cms\EventController as CmsEvent;
use App\Http\Controllers\cms\MemberController;
use App\Http\Controllers\cms\HomePageController;
use App\Http\Controllers\cms\TestimonialController;
use App\Http\Controllers\cms\ContactController;
use App\Http\Controllers\cms\ContactEmailController;

// fe
use App\Http\Controllers\fe\HomeController;
use App\Http\Controllers\fe\BlogController;
use App\Http\Controllers\fe\ContactController as ContactControllerFe;
use App\Http\Controllers\fe\LibraryController;
use App\Http\Controllers\fe\EventController;
use App\Http\Controllers\fe\AuthController as AuthControllerFe;
use App\Http\Controllers\fe\FilterController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// CMS
$domainCMS = env('DOMAIN_CMS', 'cms.localhost');
Route::domain($domainCMS)->group(function () {
    // auth
    Route::get('login', [AuthController::class, 'login'])->name('loginForm')->middleware(['guest']);
    Route::post('login/process', [AuthController::class, 'postLogin'])->name('login');
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');

    // Middleware auth login
    Route::middleware(['auth.content'])->group(function() {
        
        Route::get('/', [DashboardController::class, 'index']);
        
        // Middleware auth login role admin
        Route::middleware(['auth.admin'])->group(function() {
            // get tag
            Route::post('blog/selectTag', [CmsBlog::class, 'tag']);

            // get data json
            Route::get('user/dataJson', [UserController::class, 'dataJson']);
            Route::get('member/dataJson', [MemberController::class, 'dataJson']);
            Route::get('course/dataJson', [CourseController::class, 'dataJson']);
            Route::get('blog/dataJson', [CmsBlog::class, 'dataJson']);
            Route::get('library/dataJson', [CmsLibrary::class, 'dataJson']);
            Route::get('event/dataJson', [CmsEvent::class, 'dataJson']);
            Route::get('kategori_blog/dataJson', [KategoriBlogController::class, 'dataJson']);
            Route::get('course/dataJson', [CourseController::class, 'dataJson']);
            Route::get('testimonial/dataJson', [TestimonialController::class, 'dataJson']);
            Route::get('contact-email/dataJson', [ContactEmailController::class, 'dataJson']);

            Route::resource('user', UserController::class);
            Route::resource('member', MemberController::class);
            Route::resource('course', CourseController::class);
            Route::resource('blog', CmsBlog::class);
            Route::resource('library', CmsLibrary::class);
            Route::resource('event', CmsEvent::class);
            Route::resource('kategori_blog', KategoriBlogController::class);
            Route::resource('homepage', HomePageController::class);
            Route::resource('testimonial', TestimonialController::class);
            Route::resource('contact', ContactController::class);
            Route::resource('contact-email', ContactEmailController::class);

        });
    });

    
});

// FE
$domainFE = env('DOMAIN_FE', 'localhost');
Route::domain($domainFE)->group(function () {
    // loadmore
    Route::post('library/loadmore', [LibraryController::class, 'loadmore']);
    Route::post('blog/loadmore', [BlogController::class, 'loadmore']);
    Route::post('event/loadmore', [EventController::class, 'loadmore']);
    Route::post('search/loadmore', [FilterController::class, 'loadmore']);
    
    Route::get('/', [HomeController::class, 'index']);
    Route::get('blog', [BlogController::class, 'index']);
    Route::get('event', [EventController::class, 'index']);
    Route::get('contact', [ContactControllerFe::class, 'index']);
    Route::get('library', [LibraryController::class, 'index']);
    Route::get('search', [FilterController::class, 'search']);

    Route::get('blog/detail/{id}', [BlogController::class, 'detail']);
    Route::get('event/detail/{id}', [EventController::class, 'detail']);
    Route::post('contact/send', [ContactControllerFe::class, 'send']);
    Route::get('library/detail/{id}', [LibraryController::class, 'detail']);
    Route::get('library/download/{filename}', [LibraryController::class, 'download']);

    // auth
    Route::get('verify/{token}', [AuthControllerFe::class, 'verify']);
    
    Route::get('signup', [AuthControllerFe::class, 'signup'])->name('signup');
    Route::post('signup', [AuthControllerFe::class, 'signupProcess'])->name('signupProcess');

    Route::get('signin', [AuthControllerFe::class, 'signin'])->name('signin');
    Route::post('signin', [AuthControllerFe::class, 'signinProcess'])->name('signinProcess');

    Route::get('signout', [AuthControllerFe::class, 'signout'])->name('signout');
});

app/Models/Course.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Course extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'course';
    
    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'title',
        'link',
        'status'
    ];
}

app/Http/Controllers/cms/AuthController.php
<?php

namespace App\Http\Controllers\cms;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;

class AuthController extends Controller
{
    public function login()
    {
        if (getGuardCms() != null)
            return redirect('/');

        return view('cms.auth.login');
    }

    public function postLogin(Request $request)
    {
        $user = User::where('username', $request->username)->first();

        if ($user != null) {
            $check_login = auth()->guard($user->role)->attempt(['username' =>  $request->input('username'), 'password' => $request->input('password')]);
            if ($check_login) {
                if (auth()->guard($user->role)->user()->status != 'Aktif') {
                    auth()->guard($user->role)->logout();
                    return redirect()->route('loginForm')->with('errorss', ['Akun Tidak Aktif.']);
                } else {
                    $user = User::where('id', auth()->guard($user->role)->user()->id)->first();
                    return redirect('/')->with('success', 'Berhasil Login !! ');
                }
            } else {
                return redirect()->route('loginForm')->with('errorss', ['password salah.']);
            }
        } else {
            return redirect()->route('loginForm')->with('errorss', ['Akun tidak terdaftar.']);
        }
    }

    public function logout()
    {
        auth()->guard(getGuardCms()->role)->logout();
        return redirect()->route('loginForm');
    }
}

app/Http/Controllers/cms/BlogController.php
<?php

namespace App\Http\Controllers\cms;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Blog;
use App\Models\Tag;
use App\Models\KategoriBlog;
use DataTables;
use Image;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    function dataJson(){
        return Datatables::of(Blog::all())
        ->addColumn('action', function ($row) {
            $action = '<a style="margin-right:2px;" href="'.url('blog/'.$row->id.'/edit').'" class="btn btn-inverse-primary"><i class="bx bx-edit me-0"></i></a>';
            $action .= '<button data-remote="'.url('blog/'. $row->id).'" class="btn btn-delete btn-inverse-danger"><i class="bx bx-trash me-0"></i></button>';
            
            return $action;
        })
        ->make(true);
    }

    public function index()
    {
        $meta = [
            'title'			=> 'Blog',
			'breadcrumb'	=> [
				'Dashboard' => "/",
				'Blog'	=> null
			]
        ];

        $plugins = [
            'css' => [
                'dashboard/plugins/datatable/css/dataTables.bootstrap5.min.css',
                'dashboard/plugins/notifications/css/lobibox.min.css'
            ],
            'js' => [
                'dashboard/plugins/datatable/js/jquery.dataTables.min.js',
                'dashboard/plugins/datatable/js/dataTables.bootstrap5.min.js',
                'dashboard/plugins/notifications/js/lobibox.min.js',
                'dashboard/plugins/sweetalert/sweetalert.min.js',
                'dashboard/plugins/sweetalert/jquery.sweet-alert.custom.js',
            ]
        ];

        return view('cms.blog.index', compact('meta', 'plugins'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $meta = [
            'title'			=> 'Add Blog',
			'breadcrumb'	=> [
				'Dashboard' => "/",
				'Blog'	=> "blog",
				'Add Blog'=> null
			]
        ];

        $data = [
            "id" => "",
            "title" => "",
            "subtitle" => "",
            "foto" => "",
            "isi" => "",
            "penulis" => "",
            "kategori" => "",
            "tag" => "",
        ];

        $data = (object) $data;

        $kategori = KategoriBlog::get();

        return view('cms.blog.form', compact('meta', "data", 'kategori'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'foto' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ],
        [
            'foto.image' => 'The type of the uploaded file should be an image.',
            'foto.uploaded' => 'Failed to upload an image. The image maximum size is 2MB.'
        ]);
        
        $blog = New Blog();

        $blog->title = $request->input('title');
        $blog->subtitle = $request->input('subtitle');
        $blog->kategori = $request->input('kategori');
        $blog->isi = $request->input('isi');
        $blog->penulis = getGuardCms()->nama_lengkap;

        if ($request->tag != null) {
            $blog->tag = implode(',', $request->tag);
            
            // tag trigger to table tag
            foreach ($request->tag as $key => $value) {
                $cekTag = Tag::where('tag', $value)->first();
                if ($cekTag == null) {
                    Tag::create(['tag' => $value]);            
                }
            }
        }

        $folder = 'images/blog/';
        if ($request->file('foto')) {
            $blog->foto = uploadImg($request, 'foto', $folder);
        }
        
        $blog->save();
        return redirect()->route('blog.index')->with('success','Data Blog Berhasil Disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Blog::where('id',$id)->first();

        $meta = [
            'title'			=> 'Edit Blog',
			'breadcrumb'	=> [
				'Dashboard'     => "/",
				'Blog'		=> "blog",
				'Edit Blog'	=> ""
			]
        ];

        $kategori = KategoriBlog::get();

        return view('cms.blog.form', compact('meta', "data", 'kategori'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'foto' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ],
        [
            'foto.image' => 'The type of the uploaded file should be an image.',
            'foto.uploaded' => 'Failed to upload an image. The image maximum size is 2MB.'
        ]);
        
        $blog = [
            'title' => $request->input('title'),
            'subtitle' => $request->input('subtitle'),
            'kategori' => $request->input('kategori'),
            'isi' => $request->input('isi'),
        ];

        $getData = Blog::where('id', $id)->first();
        $nama_old = $getData->foto;
        $folder = 'images/blog/';
        if ($request->file('foto')) {
            $blog['foto'] = uploadImg($request, 'foto', $folder);
            if (file_exists($folder.$nama_old) && $nama_old != null) {
                unlink($folder.$nama_old);
            }
        }

        if ($request->tag != null) {
            $blog['tag'] = implode(',', $request->tag);
            foreach ($request->tag as $key => $value) {
                $cekTag = Tag::where('tag', $value)->first();
                if ($cekTag == null) {
                    Tag::create(['tag' => $value]);            
                }
            }
        }

        Blog::where("id", $id)->update($blog);

        return redirect()->route('blog.index')->with('success','Data Blog Berhasil Diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $blog = Blog::find($id);

        $folder = 'images/blog/';
        $nama_old = $blog->foto;
        if (file_exists($folder.$nama_old) && $nama_old != null) {
            unlink($folder.$nama_old);
        }

        $blog->delete();
        return 'success';
    }

    // tag using select2
    public function tag(Request $request)
    {
        $data = Tag::select('id', 'tag')->limit(5)->get();

        if($request->has('q')){
            $term = $request->q;
            $data = Tag::select('id', 'tag')->where('tag','LIKE','%'.$term.'%')->limit(5)->get();
        }

        return response()->json($data);
    }
}

app/Http/Controllers/cms/ContactController.php
<?php

namespace App\Http\Controllers\cms;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\SiteManagement;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $meta = [
            'title'			=> 'Contact',
			'breadcrumb'	=> [
				'Dashboard' => "/",
				'Contact'	=> null
			]
        ];

        $plugins = [
            'js' => [
                'dashboard/plugins/sweetalert/sweetalert.min.js',
                'dashboard/plugins/sweetalert/jquery.sweet-alert.custom.js',
            ]
        ];

        $data = SiteManagement::where('keyname', 'contact')->first();

        if (!$data) {
            $data['value'] = [
                'address' => '',
                'phone' => '',
                'email' => '',
            ];

            $data['value'] = (object) $data['value'];
        } else {
            $data = ['value' => json_decode($data->value)];
        }

        return view('cms.contact.index', compact('meta', 'plugins', 'data'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'address' => 'required',
            'phone' =>'required',
            'email' =>'required'
        ]);

        SiteManagement::updateOrCreate(
            ['section' => 'site', 'keyname' => 'contact'],
            [
                'value' => json_encode([
                    'address' => $request->address,
                    'phone' => $request->phone,
                    'email' => $request->email,
                ])
            ]
        );

        return redirect()->route('contact.index')->with('success','Data Contact Berhasil Disimpan');
    }
}

app/Http/Controllers/cms/DashboardController.php
<?php

namespace App\Http\Controllers\cms;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        $meta = [
            'title' => 'Dashboard'
        ];

        $plugins = [
            'css' => [
                'dashboard/plugins/vectormap/jquery-jvectormap-2.0.2.css'
            ],
            'js' => [
                'dashboard/plugins/vectormap/jquery-jvectormap-2.0.2.min.js',
                'dashboard/plugins/vectormap/jquery-jvectormap-world-mill-en.js',
                'dashboard/plugins/chartjs/js/Chart.min.js',
                'dashboard/plugins/chartjs/js/Chart.extension.js',
                'dashboard/js/index.js',
            ]
        ];

        return view('cms/dashboard.index', compact('meta', 'plugins'));
    }
}

resources/views/cms/course/form.blade.php
@extends('cms.layouts.base')

@section('content')
    <div class="card border-top border-0 border-4 border-primary" id="addedit">
        <div class="card-body p-5">
            <div class="card-title d-flex align-items-center">
                <div><i class="bx bxs-book-add me-1 font-22 text-primary"></i></div>
                <h5 class="mb-0 text-primary">{{ $meta['title'] }}</h5>
            </div>
            <hr>
            @if (!$data->id)
                <form method="POST" class="row g-3" action="{{ route('course.store') }}">
            @else
                <form method="POST" class="row g-3" action="{{ url('course/' . $data->id) }}">
                    {{ method_field('PUT') }}
            @endif
            @csrf
            @include('cms.layouts.validation_error')
                <div class="col-md-6" id="colusername">
                    <label for="inputTitle" class="form-label">Title</label>
                    <input type="text" name="title" class="form-control" id="inputTitle" value="{{ $data->title }}" required>
                </div>
                <div class="col-md-6">
                    <label for="inputLink" class="form-label">Link</label>
                    <input type="text" name="link" class="form-control" id="inputLink" value="{{ $data->link }}" required>
                </div>
                <div class="col-md-6">
                    <label for="inputStatus" class="form-label">Status</label>
                    <select id="inputStatus" name="status" class="form-select" required>
                        <option value="Aktif" {{ $data->status == 'Aktif' ? 'selected' : '' }}>Aktif</option>
                        <option value="Tidak Aktif" {{ $data->status == 'Tidak Aktif' ? 'selected' : '' }}>Tidak Aktif</option>
                    </select>
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-inverse-primary px-5">Save</button>
                    <a href="{{ url('course') }}" class="btn btn-inverse-danger px-5">Cancel</a>
                </div>
            </form>
        </div>
    </div>

    @include('sweetalert::alert')

@endsection

resources/views/cms/course/index.blade.php
@extends('cms.layouts.base')

@section('content')
    <div class="card">
        <div class="card-header d-flex py-3">
            <h4>Course</h4>
            <a href="{{ url('course/create') }}" class="btn btn-inverse-primary ms-auto">Add</a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table id="table-course" class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Link</th>
                            <th width="125" class="text-center">Status</th>
                            <th width="125" class="text-center">Action</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>

    @include('sweetalert::alert')

@endsection

@section('sectionFooter')
    <script>
        $(function() {
            $("#table-course").DataTable({
                processing: true,
                serverSide: true,
                ajax: "/course/dataJson",
                columns: [
                    // { data: "id", name: "id" },
                    {
                        data: "title",
                        name: "title"
                    },
                    {
                        data: "link",
                        name: "link"
                    },
                    {
                        data: "status",
                        render: function(data, type, row) {
                            if (data == "Aktif") {
                                return '<span class="btn btn-inverse-success">Aktif</span>';
                            } else {
                                return '<span class="btn btn-inverse-danger">Tidak Aktif</span>';
                            }
                        },
                        className: 'text-center',
                    },
                    {
                        data: "action",
                        name: "action",
                        className: 'text-center'
                    },
                ],
            });

            $("#table-course").on("click", ".btn-delete[data-remote]", function(e) {
                e.preventDefault();
                var url = $(this).data("remote");
                console.log(url);
                swal({
                        title: "Apakah yakin?",
                        text: "Mengapus data user !!",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "Yes, delete it!",
                        closeOnConfirm: false,
                    },
                    function() {
                        console.log(url);
                        $.ajax({
                            url: url,
                            type: "DELETE",
                            dataType: "json",
                            data: {
                                method: "_DELETE",
                                submit: true,
                                _token: "{{ csrf_token() }}",
                            },
                        }).always(function(data) {
                            $("#table-course").DataTable().draw(false);
                            swal("Sukses !!", "Menghapus data user.", "success");
                        });
                    }
                );
            });
        });
    </script>
@endsection